import React from "react";

function TGAContents() {
    return(
        <div>
            <h3>TGA Contents</h3>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
            <p>sdlkfjksadjfkjhfks</p>
        </div>
    )
}
export default TGAContents;